# Change these first
owner: EnderdracheLP # Your GitHub organization or username, where this repository lives
repo: Beat-Saber-Uptime # The name of this repository
user-agent: Beat-Saber-Uptime-Checker+(https://github.com/EnderdracheLP/Beat-Saber-Uptime/)

sites:
  - name: BeastSaber
    url: https://bsaber.com
    icon: https://bsaber.com/wp-content/uploads/2018/07/cropped-Beastsaber-Site-Icon-300x300.png
  - name: BeatSaver
    url: https://beatsaver.com
    icon: https://raw.githubusercontent.com/EnderdracheLP/Beat-Saber-Uptime/master/assets/BeatSaverLogoCube.png
  - name: QuestBoard
    url: https://www.questmodding.com
    icon: https://www.questmodding.com/icon.png
  - name: BeatMods
    url: https://beatmods.com/
    icon: https://raw.githubusercontent.com/EnderdracheLP/Beat-Saber-Uptime/master/assets/BeatModsLogo.png
  - name: BMBF
    url: https://bmbf.dev
    icon: https://raw.githubusercontent.com/EnderdracheLP/Beat-Saber-Uptime/master/assets/BMBF_Icon.png
  - name: ModelSaber
    url: https://modelsaber.com
    icon: https://modelsaber.com/resources/manifest/icon-512.png
  - name: ScoreSaber
    url: https://scoresaber.com
    icon: https://scoresaber.com/imports/images/logo.ico
  - name: BSMG Wiki
    url: https://bsmg.wiki
    icon: https://bsmg.wiki/favicon.png
  - name: QPackages (Backend)
    url: https://qpackages.com/
  - name: Bobbie.dev
    url: https://bobbie.dev/
    icon: https://bobbie.dev/favicon.ico
  - name: Beat Saber Legacy
    url: https://bslegacy.com
    icon: https://bslegacy.com/img/block.png
  - name: OculusDB
    url: https://oculusdb.rui2015.me/
    icon: https://oculusdb.rui2015.me/favicon.ico
  - name: Official MP Server Status - ProductionA
    url: $BS_PRODA
    icon: https://beatsaber.com/images/favicon/favicon.ico
    __dangerous__body_down: '"status":2'
  - name: Official MP Server Status - ProductionB
    url: $BS_PRODB
    icon: https://beatsaber.com/images/favicon/favicon.ico
    __dangerous__body_down: '"status":2'
  - name: Beat Together Server Status
    url: $BT_STATUS
    icon: https://cdn.discordapp.com/avatars/782351281985552466/3357bcf464313696ae7ac380afbe9fa1.png
    __dangerous__body_down: '"status":2'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.elp.quest
  # themeUrl: https://raw.githubusercontent.com/EnderdracheLP/Beat-Saber-Uptime/master/assets/custom_dark.css
  theme: night
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Beat Saber Uptime
  introTitle: "**Beat Saber Uptime** Status for Beat Saber Official and Unofficial Services."
  introMessage: This is the current status of Beat Saber and Beat Saber modding related sites and Services
  navbar:
    - title: Main Site
      href: https://EnderdracheLP.elp.quest
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  responseTime: "0 */12 * * *"
  uptime: "*/10 * * * *"
  # Update responseTime every 12 hours instead of every day at 23:00
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
